### ISSUE TITLE
PeerDep warning + duplicate plugin errors

### ISSUE THREAD

**Issue by StevenLangbroek** [akameco/extract-react-intl#17]
- version: extract-react-intl-0.6.0.tgz#1696c2ce05513d936272af4b6663700df8414b55
- `node` version: 8.11
- `npm` (or `yarn`) version: yarn 

**Do you want to request a *feature* or report a *bug*?:**
Bug

**What is the current behavior?:**
```bash
$ extract-messages -l=source -o server/lang -d source --flat 'src/**/!(*.test).js'
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
    at assertNoDuplicates (/Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/config-descriptors.js:205:13)
    at createDescriptors (/Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
    at createPluginDescriptors (/Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/caching.js:33:19)
    at plugins.plugins (/Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/Users/stevenlangbroek/Code/ec_portal/node_modules/@babel/core/lib/config/partial.js:85:55)
error Command failed with exit code 1.
```

**What is the expected behavior?:**
We're running babel 7 in our project, so I followed the instruction re: `babel-core@bridge`. Unfortunately the error still persists. I added some logging, and `name` in the `assertNoDuplicated` function is empty (these are added to a map to verify lack of duplication).

**Suggested solution:**
I'm not sure why it's still using "@babel/core" instead of `babel-core`, despite `babel-core@bridge` being installed. Any thoughts>

**Comment by akameco** [comment]
@StevenLangbroek Fixed. We dropped babel 6. You do not need babel-core or @babel/core.
